spring:
  datasource:
    url: jdbc:mysql://192.168.41.66:3306/content_center
    hikari:
      username: root
      password: root
      # >= 6.x com.mysql.cj.jdbc.Driver
      # <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: BJ
        # namespace: ff785bbf-2022-48a9-8883-0e00e75688ac
        # 设置元数据
#        metadata:
          # 自己这个实例的版本
#          version: v1
          # 允许调用的提供者版本
#          target-version: v1
    sentinel:
#      datasource:
#        # 名称随意
#        flow:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-flow-rules
#            groupId: SENTINEL_GROUP
#            # 规则类型，取值见：
#            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
#            rule-type: flow
#        degrade:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-degrade-rules
#            groupId: SENTINEL_GROUP
#            rule-type: degrade
#        system:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-system-rules
#            groupId: SENTINEL_GROUP
#            rule-type: system
#        authority:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-authority-rules
#            groupId: SENTINEL_GROUP
#            rule-type: authority
#        param-flow:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-param-flow-rules
#            groupId: SENTINEL_GROUP
#            rule-type: param-flow
      filter:
        # 打开(true)/关闭(false)对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
  application:
    # 服务名称尽量用 - ，不要用 _ ，不要用特殊符号
    name: content-center
  # 解决 @FeignClient(多个name 指定同一个微服务)
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    # 开启饥饿加载。ribbon默认是懒加载 导致第一次加载很慢
    enabled: true
    # 指定那个微服务使用饥饿加载，多个使用 "xxx,xxx,xxx"，没被指定的都是懒加载
    clients: user-center
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 想要调用的微服务的名称
      #user-center:
      # 全局配置
      default:
        loggerLevel: full
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'
resttemplate:
  sentinel:
    # 关闭 @SentinelRestTemplate注解 enabled: false
    enabled: true

##指定您要接入的特定的 AHAS 环境
#ahas.namespace: default
##自定义您的应用名称
#project.name: conten-center
##配置 license 信息
#ahas.license: 4523495f8d0e4a0aaf86e6825fbc0708